# DevContainer構成用docker-compose

version: '3.6'

services:
    devcontainer:
        build:
            context: ../
            dockerfile: Dockerfile
        tty: true
        volumes:
            - type: bind 
              source: ../
              target: /workspace/
            - type: volume
              source: app_data
              target: /workspace/data
            - type: bind
              source: ../entrypoint/
              target: /entrypoint/
            - type: bind
              source: ../postfix/main.cf
              target: /etc/postfix/main.cf
            - type: bind
              source: ../postfix/master.cf
              target: /etc/postfix/master.cf
            - type: bind
              source: ../postfix/transport
              target: /etc/postfix/transport
        environment:
            LANG: ja_JP.UTF-8
            DEBUG: 1

volumes:
    app_data: